#!/usr/bin/env bash
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

if [ -f /root/miniconda3/etc/profile.d/conda.sh ]; then
  # shellcheck disable=SC1091
  source /root/miniconda3/etc/profile.d/conda.sh
  conda activate "${CONDA_ENV:-internevo}"
fi

export INTERNLM_ACCELERATOR="${INTERNLM_ACCELERATOR:-npu}"

NNODES="${NNODES:-1}"
NODE_RANK="${NODE_RANK:-0}"
GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
MASTER_ADDR="${MASTER_ADDR:-127.0.0.1}"
MASTER_PORT="${MASTER_PORT:-29500}"

CONFIG="${CONFIG:-configs/test_to10m_pity/7Binternlm2_seq_step_pp_hp_cp.py}"

CFG_SEQ_LEN="${CFG_SEQ_LEN:-$((1024 * 64))}"
CFG_TOTAL_STEPS="${CFG_TOTAL_STEPS:-3}"
CFG_PP_SIZE="${CFG_PP_SIZE:-1}"
CFG_HEAD_SIZE="${CFG_HEAD_SIZE:-2}"
CFG_CONTEXT_SIZE="${CFG_CONTEXT_SIZE:-8}"
CFG_WINDOW_SIZE="${CFG_WINDOW_SIZE:-1}"
CFG_USE_FLASH_ATTN="${CFG_USE_FLASH_ATTN:-True}"
CFG_NPU_FIXEDLEN_FLASH_2D="${CFG_NPU_FIXEDLEN_FLASH_2D:-True}"
CFG_OVERLAP_SYNC_GRAD="${CFG_OVERLAP_SYNC_GRAD:-False}"
CFG_OVERLAP_SYNC_PARAM="${CFG_OVERLAP_SYNC_PARAM:-False}"
CFG_FIXED_RANDOM_DATASET_SEQLEN="${CFG_FIXED_RANDOM_DATASET_SEQLEN:-True}"
CFG_EMPTY_CACHE_AND_DIAG_INTERVAL="${CFG_EMPTY_CACHE_AND_DIAG_INTERVAL:-200}"

SEQ_K=$((CFG_SEQ_LEN / 1024))
FLASH_TAG=""
if [ "${CFG_USE_FLASH_ATTN}" != "False" ] || [ "${CFG_NPU_FIXEDLEN_FLASH_2D}" != "False" ]; then
  FLASH_TAG="_fa${CFG_USE_FLASH_ATTN}_npu2d${CFG_NPU_FIXEDLEN_FLASH_2D}"
fi
_LAUNCH_TIMESTAMP=`date +%Y%m%d%H%M%S`
LOG_NAME="${LOG_NAME:-${_LAUNCH_TIMESTAMP}_seq${SEQ_K}k_steps${CFG_TOTAL_STEPS}_pp${CFG_PP_SIZE}_h${CFG_HEAD_SIZE}_c${CFG_CONTEXT_SIZE}_ws${CFG_WINDOW_SIZE}${FLASH_TAG}}"

export CFG_SEQ_LEN CFG_TOTAL_STEPS CFG_PP_SIZE CFG_HEAD_SIZE CFG_CONTEXT_SIZE CFG_WINDOW_SIZE CFG_USE_FLASH_ATTN CFG_NPU_FIXEDLEN_FLASH_2D CFG_OVERLAP_SYNC_GRAD CFG_OVERLAP_SYNC_PARAM CFG_FIXED_RANDOM_DATASET_SEQLEN CFG_EMPTY_CACHE_AND_DIAG_INTERVAL LOG_NAME

mkdir -p log

echo "CONFIG=${CONFIG}"
echo "LOG=log/${LOG_NAME}.log"
echo "NNODES=${NNODES} NODE_RANK=${NODE_RANK} GPUS_PER_NODE=${GPUS_PER_NODE}"
echo "MASTER_ADDR=${MASTER_ADDR} MASTER_PORT=${MASTER_PORT}"
echo "CFG_SEQ_LEN=${CFG_SEQ_LEN} CFG_TOTAL_STEPS=${CFG_TOTAL_STEPS}"
echo "CFG_PP_SIZE=${CFG_PP_SIZE} CFG_HEAD_SIZE=${CFG_HEAD_SIZE} CFG_CONTEXT_SIZE=${CFG_CONTEXT_SIZE} CFG_WINDOW_SIZE=${CFG_WINDOW_SIZE}"
echo "CFG_USE_FLASH_ATTN=${CFG_USE_FLASH_ATTN} CFG_NPU_FIXEDLEN_FLASH_2D=${CFG_NPU_FIXEDLEN_FLASH_2D}"
echo "CFG_OVERLAP_SYNC_GRAD=${CFG_OVERLAP_SYNC_GRAD} CFG_OVERLAP_SYNC_PARAM=${CFG_OVERLAP_SYNC_PARAM} CFG_FIXED_RANDOM_DATASET_SEQLEN=${CFG_FIXED_RANDOM_DATASET_SEQLEN}"
echo "CFG_EMPTY_CACHE_AND_DIAG_INTERVAL=${CFG_EMPTY_CACHE_AND_DIAG_INTERVAL}"

torchrun \
  --nnodes "${NNODES}" \
  --nproc-per-node "${GPUS_PER_NODE}" \
  --node_rank "${NODE_RANK}" \
  --master-addr "${MASTER_ADDR}" \
  --master-port "${MASTER_PORT}" \
  train.py \
  --config "${CONFIG}" \
  --launcher torch \
  2>&1 | tee "log/${LOG_NAME}.log"

exit "${PIPESTATUS[0]}"
